//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Fri May  5 21:25:45 IST 2023
//
//
// Ports:
// Name                         I/O  size props
// RDY_get_inputs                 O     1
// mac_result                     O    64
// RDY_mac_result                 O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// get_inputs_multiplicand1       I    32
// get_inputs_multiplicand2       I    32
// get_inputs_addend              I    32
// get_inputs_mode                I     1 reg
// EN_get_inputs                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMAC32(CLK,
	       RST_N,

	       get_inputs_multiplicand1,
	       get_inputs_multiplicand2,
	       get_inputs_addend,
	       get_inputs_mode,
	       EN_get_inputs,
	       RDY_get_inputs,

	       mac_result,
	       RDY_mac_result);
  input  CLK;
  input  RST_N;

  // action method get_inputs
  input  [31 : 0] get_inputs_multiplicand1;
  input  [31 : 0] get_inputs_multiplicand2;
  input  [31 : 0] get_inputs_addend;
  input  get_inputs_mode;
  input  EN_get_inputs;
  output RDY_get_inputs;

  // value method mac_result
  output [63 : 0] mac_result;
  output RDY_mac_result;

  // signals for module outputs
  wire [63 : 0] mac_result;
  wire RDY_get_inputs, RDY_mac_result;

  // inlined wires
  wire [160 : 0] partial_product_rv$port1__read,
		 partial_product_rv$port1__write_1,
		 partial_product_rv$port2__read;
  wire [96 : 0] mac_inputs_rv$port1__read,
		mac_inputs_rv$port1__write_1,
		mac_inputs_rv$port2__read;
  wire [64 : 0] mac_output_rv$port1__write_1, mac_output_rv$port2__read;
  wire mac_output_rv$EN_port1__write, partial_product_rv$EN_port0__write;

  // register mac_inputs_rv
  reg [96 : 0] mac_inputs_rv;
  wire [96 : 0] mac_inputs_rv$D_IN;
  wire mac_inputs_rv$EN;

  // register mac_output_rv
  reg [64 : 0] mac_output_rv;
  wire [64 : 0] mac_output_rv$D_IN;
  wire mac_output_rv$EN;

  // register mode_r
  reg mode_r;
  wire mode_r$D_IN, mode_r$EN;

  // register partial_product_rv
  reg [160 : 0] partial_product_rv;
  wire [160 : 0] partial_product_rv$D_IN;
  wire partial_product_rv$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_add_partials,
       CAN_FIRE_RL_rl_generate_partials,
       CAN_FIRE_RL_rl_mac_16,
       CAN_FIRE_get_inputs,
       WILL_FIRE_RL_rl_add_partials,
       WILL_FIRE_RL_rl_generate_partials,
       WILL_FIRE_RL_rl_mac_16,
       WILL_FIRE_get_inputs;

  // inputs to muxes for submodule ports
  wire [64 : 0] MUX_mac_output_rv$port1__write_1__VAL_1,
		MUX_mac_output_rv$port1__write_1__VAL_2;

  // remaining internal signals
  wire [63 : 0] _0_CONCAT_mac_inputs_rv_port0__read_BITS_79_TO__ETC___d11,
		_0_CONCAT_mac_inputs_rv_port0__read_BITS_79_TO__ETC___d15,
		_0_CONCAT_mac_inputs_rv_port0__read_BITS_95_TO__ETC___d19,
		_0_CONCAT_mac_inputs_rv_port0__read_BITS_95_TO__ETC___d21,
		x__h1323,
		x__h1325,
		x__h1327,
		y__h1324,
		y__h1326,
		y__h1328;
  wire [31 : 0] x__h1398, y__h1548, y__h1584;

  // action method get_inputs
  assign RDY_get_inputs = !mac_inputs_rv$port1__read[96] ;
  assign CAN_FIRE_get_inputs = !mac_inputs_rv$port1__read[96] ;
  assign WILL_FIRE_get_inputs = EN_get_inputs ;

  // value method mac_result
  assign mac_result = mac_output_rv[63:0] ;
  assign RDY_mac_result = mac_output_rv[64] ;

  // rule RL_rl_add_partials
  assign CAN_FIRE_RL_rl_add_partials =
	     partial_product_rv[160] && !mac_output_rv[64] && mode_r ;
  assign WILL_FIRE_RL_rl_add_partials = CAN_FIRE_RL_rl_add_partials ;

  // rule RL_rl_mac_16
  assign CAN_FIRE_RL_rl_mac_16 =
	     partial_product_rv[160] && !mac_output_rv[64] && !mode_r ;
  assign WILL_FIRE_RL_rl_mac_16 = CAN_FIRE_RL_rl_mac_16 ;

  // rule RL_rl_generate_partials
  assign CAN_FIRE_RL_rl_generate_partials =
	     mac_inputs_rv[96] && !partial_product_rv$port1__read[160] ;
  assign WILL_FIRE_RL_rl_generate_partials =
	     CAN_FIRE_RL_rl_generate_partials ;

  // inputs to muxes for submodule ports
  assign MUX_mac_output_rv$port1__write_1__VAL_1 =
	     { 1'd1, x__h1323 + y__h1324 } ;
  assign MUX_mac_output_rv$port1__write_1__VAL_2 =
	     { 1'd1,
	       partial_product_rv[63:32] + y__h1548,
	       partial_product_rv[159:128] + y__h1584 } ;

  // inlined wires
  assign mac_inputs_rv$port1__read =
	     CAN_FIRE_RL_rl_generate_partials ?
	       97'h0AAAAAAAAAAAAAAAAAAAAAAAA :
	       mac_inputs_rv ;
  assign mac_inputs_rv$port1__write_1 =
	     { 1'd1,
	       get_inputs_multiplicand1,
	       get_inputs_multiplicand2,
	       get_inputs_addend } ;
  assign mac_inputs_rv$port2__read =
	     EN_get_inputs ?
	       mac_inputs_rv$port1__write_1 :
	       mac_inputs_rv$port1__read ;
  assign partial_product_rv$EN_port0__write =
	     WILL_FIRE_RL_rl_mac_16 || WILL_FIRE_RL_rl_add_partials ;
  assign partial_product_rv$port1__read =
	     partial_product_rv$EN_port0__write ?
	       161'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA :
	       partial_product_rv ;
  assign partial_product_rv$port1__write_1 =
	     { 1'd1,
	       _0_CONCAT_mac_inputs_rv_port0__read_BITS_79_TO__ETC___d11[31:0],
	       _0_CONCAT_mac_inputs_rv_port0__read_BITS_79_TO__ETC___d15[31:0],
	       _0_CONCAT_mac_inputs_rv_port0__read_BITS_95_TO__ETC___d19[31:0],
	       _0_CONCAT_mac_inputs_rv_port0__read_BITS_95_TO__ETC___d21[31:0],
	       mac_inputs_rv[31:0] } ;
  assign partial_product_rv$port2__read =
	     CAN_FIRE_RL_rl_generate_partials ?
	       partial_product_rv$port1__write_1 :
	       partial_product_rv$port1__read ;
  assign mac_output_rv$EN_port1__write =
	     WILL_FIRE_RL_rl_add_partials || WILL_FIRE_RL_rl_mac_16 ;
  assign mac_output_rv$port1__write_1 =
	     WILL_FIRE_RL_rl_add_partials ?
	       MUX_mac_output_rv$port1__write_1__VAL_1 :
	       MUX_mac_output_rv$port1__write_1__VAL_2 ;
  assign mac_output_rv$port2__read =
	     mac_output_rv$EN_port1__write ?
	       mac_output_rv$port1__write_1 :
	       mac_output_rv ;

  // register mac_inputs_rv
  assign mac_inputs_rv$D_IN = mac_inputs_rv$port2__read ;
  assign mac_inputs_rv$EN = 1'b1 ;

  // register mac_output_rv
  assign mac_output_rv$D_IN = mac_output_rv$port2__read ;
  assign mac_output_rv$EN = 1'b1 ;

  // register mode_r
  assign mode_r$D_IN = get_inputs_mode ;
  assign mode_r$EN = EN_get_inputs ;

  // register partial_product_rv
  assign partial_product_rv$D_IN = partial_product_rv$port2__read ;
  assign partial_product_rv$EN = 1'b1 ;

  // remaining internal signals
  assign _0_CONCAT_mac_inputs_rv_port0__read_BITS_79_TO__ETC___d11 =
	     { 16'd0, mac_inputs_rv[79:64] } *
	     { 16'd0, mac_inputs_rv[47:32] } ;
  assign _0_CONCAT_mac_inputs_rv_port0__read_BITS_79_TO__ETC___d15 =
	     { 16'd0, mac_inputs_rv[79:64] } *
	     { 16'd0, mac_inputs_rv[63:48] } ;
  assign _0_CONCAT_mac_inputs_rv_port0__read_BITS_95_TO__ETC___d19 =
	     { 16'd0, mac_inputs_rv[95:80] } *
	     { 16'd0, mac_inputs_rv[47:32] } ;
  assign _0_CONCAT_mac_inputs_rv_port0__read_BITS_95_TO__ETC___d21 =
	     { 16'd0, mac_inputs_rv[95:80] } *
	     { 16'd0, mac_inputs_rv[63:48] } ;
  assign x__h1323 = x__h1325 + y__h1326 ;
  assign x__h1325 = x__h1327 + y__h1328 ;
  assign x__h1327 = { 32'd0, partial_product_rv[159:128] } ;
  assign x__h1398 = partial_product_rv[127:96] + partial_product_rv[95:64] ;
  assign y__h1324 = { 32'd0, partial_product_rv[31:0] } ;
  assign y__h1326 = { partial_product_rv[63:32], 32'd0 } ;
  assign y__h1328 = { 16'd0, x__h1398, 16'd0 } ;
  assign y__h1548 = { 16'd0, partial_product_rv[31:16] } ;
  assign y__h1584 = { 16'd0, partial_product_rv[15:0] } ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        mac_inputs_rv <= `BSV_ASSIGNMENT_DELAY 97'h0AAAAAAAAAAAAAAAAAAAAAAAA;
	mac_output_rv <= `BSV_ASSIGNMENT_DELAY 65'h0AAAAAAAAAAAAAAAA;
	mode_r <= `BSV_ASSIGNMENT_DELAY 1'd0;
	partial_product_rv <= `BSV_ASSIGNMENT_DELAY
	    161'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
      end
    else
      begin
        if (mac_inputs_rv$EN)
	  mac_inputs_rv <= `BSV_ASSIGNMENT_DELAY mac_inputs_rv$D_IN;
	if (mac_output_rv$EN)
	  mac_output_rv <= `BSV_ASSIGNMENT_DELAY mac_output_rv$D_IN;
	if (mode_r$EN) mode_r <= `BSV_ASSIGNMENT_DELAY mode_r$D_IN;
	if (partial_product_rv$EN)
	  partial_product_rv <= `BSV_ASSIGNMENT_DELAY partial_product_rv$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    mac_inputs_rv = 97'h0AAAAAAAAAAAAAAAAAAAAAAAA;
    mac_output_rv = 65'h0AAAAAAAAAAAAAAAA;
    mode_r = 1'h0;
    partial_product_rv = 161'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkMAC32

